//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodo7o.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pomodo7o.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon icon_pause {
            get {
                object obj = ResourceManager.GetObject("icon_pause", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon_play {
            get {
                object obj = ResourceManager.GetObject("icon_play", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon_reset {
            get {
                object obj = ResourceManager.GetObject("icon_reset", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon_rest {
            get {
                object obj = ResourceManager.GetObject("icon_rest", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon_tomato {
            get {
                object obj = ResourceManager.GetObject("icon_tomato", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon icon_tomato_rest {
            get {
                object obj = ResourceManager.GetObject("icon_tomato_rest", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_angry {
            get {
                object obj = ResourceManager.GetObject("image_angry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://github.com/jonfuller/pomodo7o/issues.
        /// </summary>
        internal static string JumpList_Bug_Path {
            get {
                return ResourceManager.GetString("JumpList_Bug_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Bug.
        /// </summary>
        internal static string JumpList_Bug_Title {
            get {
                return ResourceManager.GetString("JumpList_Bug_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.twitter.com/jon_fuller.
        /// </summary>
        internal static string JumpList_Contact_Path {
            get {
                return ResourceManager.GetString("JumpList_Contact_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet Me.
        /// </summary>
        internal static string JumpList_Contact_Title {
            get {
                return ResourceManager.GetString("JumpList_Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://github.com/jonfuller/pomodo7o/downloads.
        /// </summary>
        internal static string JumpList_Download_Path {
            get {
                return ResourceManager.GetString("JumpList_Download_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string JumpList_Download_Title {
            get {
                return ResourceManager.GetString("JumpList_Download_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://pomodo7o.uservoice.com/forums/40667-general.
        /// </summary>
        internal static string JumpList_Feature_Path {
            get {
                return ResourceManager.GetString("JumpList_Feature_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a Feature.
        /// </summary>
        internal static string JumpList_Feature_Title {
            get {
                return ResourceManager.GetString("JumpList_Feature_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://github.com/jonfuller/pomodo7o.
        /// </summary>
        internal static string JumpList_Fork_Path {
            get {
                return ResourceManager.GetString("JumpList_Fork_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork Me!.
        /// </summary>
        internal static string JumpList_Fork_Title {
            get {
                return ResourceManager.GetString("JumpList_Fork_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Mode_Pause {
            get {
                return ResourceManager.GetString("Mode_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Time.
        /// </summary>
        internal static string Mode_Rest {
            get {
                return ResourceManager.GetString("Mode_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time.
        /// </summary>
        internal static string Mode_Work {
            get {
                return ResourceManager.GetString("Mode_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap!.
        /// </summary>
        internal static string NotSupported_Title {
            get {
                return ResourceManager.GetString("NotSupported_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Break.
        /// </summary>
        internal static string ToolTip_GoToRest {
            get {
                return ResourceManager.GetString("ToolTip_GoToRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Work.
        /// </summary>
        internal static string ToolTip_GoToWork {
            get {
                return ResourceManager.GetString("ToolTip_GoToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string ToolTip_Pause {
            get {
                return ResourceManager.GetString("ToolTip_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string ToolTip_Play {
            get {
                return ResourceManager.GetString("ToolTip_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ToolTip_Reset {
            get {
                return ResourceManager.GetString("ToolTip_Reset", resourceCulture);
            }
        }
    }
}
