//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Growler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Growler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomodo7o.
        /// </summary>
        internal static string Growl_Application {
            get {
                return ResourceManager.GetString("Growl_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Time Completed.
        /// </summary>
        internal static string NotificationDisplay_RestComplete {
            get {
                return ResourceManager.GetString("NotificationDisplay_RestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Time Started.
        /// </summary>
        internal static string NotificationDisplay_RestStart {
            get {
                return ResourceManager.GetString("NotificationDisplay_RestStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time Completed.
        /// </summary>
        internal static string NotificationDisplay_WorkComplete {
            get {
                return ResourceManager.GetString("NotificationDisplay_WorkComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time Started.
        /// </summary>
        internal static string NotificationDisplay_WorkStart {
            get {
                return ResourceManager.GetString("NotificationDisplay_WorkStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POMODO7O_REST_COMPLETE.
        /// </summary>
        internal static string NotificationType_RestComplete {
            get {
                return ResourceManager.GetString("NotificationType_RestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POMODO7O_REST_START.
        /// </summary>
        internal static string NotificationType_RestStart {
            get {
                return ResourceManager.GetString("NotificationType_RestStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POMODO7O_WORK_COMPLETE.
        /// </summary>
        internal static string NotificationType_WorkComplete {
            get {
                return ResourceManager.GetString("NotificationType_WorkComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POMODO7O_WORK_START.
        /// </summary>
        internal static string NotificationType_WorkStart {
            get {
                return ResourceManager.GetString("NotificationType_WorkStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring!  Break&apos;s Over!.
        /// </summary>
        internal static string Title_RestComplete {
            get {
                return ResourceManager.GetString("Title_RestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get breaking!.
        /// </summary>
        internal static string Title_RestStart {
            get {
                return ResourceManager.GetString("Title_RestStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whew... take a break..
        /// </summary>
        internal static string Title_WorkComplete {
            get {
                return ResourceManager.GetString("Title_WorkComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get to work!.
        /// </summary>
        internal static string Title_WorkStart {
            get {
                return ResourceManager.GetString("Title_WorkStart", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tomato_pause {
            get {
                object obj = ResourceManager.GetObject("tomato_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tomato_rest {
            get {
                object obj = ResourceManager.GetObject("tomato_rest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tomato_work {
            get {
                object obj = ResourceManager.GetObject("tomato_work", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
